/* Generated By:JJTree: Do not edit this line. ASTEq.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=izanagi.expr.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package izanagi.expr.parser;

public
class ASTEq extends SimpleNode {
  public ASTEq(int id) {
    super(id);
  }

  public ASTEq(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f855c859f1f3b19ef64cd200b970442a (do not edit this line) */
