/* Generated By:JJTree: Do not edit this line. ASTGe.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=izanagi.expr.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package izanagi.expr.parser;

public
class ASTGe extends SimpleNode {
  public ASTGe(int id) {
    super(id);
  }

  public ASTGe(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=33d2c502c83850c8c4b9db315918ebcb (do not edit this line) */
