/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 6.0_1 */
package izanagi.expr.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTEQ = 2;
  public int JJTNEQ = 3;
  public int JJTGE = 4;
  public int JJTGT = 5;
  public int JJTLE = 6;
  public int JJTLT = 7;
  public int JJTADD = 8;
  public int JJTSUB = 9;
  public int JJTMUL = 10;
  public int JJTDIV = 11;
  public int JJTMOD = 12;
  public int JJTPOWER = 13;
  public int JJTAND = 14;
  public int JJTOR = 15;
  public int JJTNOT = 16;
  public int JJTUNIEXPR = 17;
  public int JJTINTEGER = 18;
  public int JJTFLOAT = 19;
  public int JJTSTRING = 20;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Eq",
    "NEq",
    "Ge",
    "Gt",
    "Le",
    "Lt",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Mod",
    "Power",
    "And",
    "Or",
    "Not",
    "UniExpr",
    "Integer",
    "Float",
    "String",
  };
}
/* JavaCC - OriginalChecksum=bebb78895b764e3061428106b407e1df (do not edit this line) */
