/* Generated By:JavaCC: Do not edit this line. ExprParserVisitor.java Version 6.0_1 */
package izanagi.expr.parser;

public interface ExprParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTEq node, Object data);
  public Object visit(ASTNEq node, Object data);
  public Object visit(ASTGe node, Object data);
  public Object visit(ASTGt node, Object data);
  public Object visit(ASTLe node, Object data);
  public Object visit(ASTLt node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTMul node, Object data);
  public Object visit(ASTDiv node, Object data);
  public Object visit(ASTMod node, Object data);
  public Object visit(ASTPower node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTUniExpr node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTFloat node, Object data);
  public Object visit(ASTString node, Object data);
}
/* JavaCC - OriginalChecksum=ddf409799fbc65114df07f771a3feea6 (do not edit this line) */
