/* Generated By:JJTree: Do not edit this line. ASTStmt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=tk.oknctict.izanagi.shell.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tk.oknctict.izanagi.parser;

public
class ASTStmt extends SimpleNode {
  public ASTStmt(int id) {
    super(id);
  }

  public ASTStmt(ExprParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExprParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=680083fbbab72c83967ae01281c549df (do not edit this line) */
