/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 6.0_1 */
package tk.oknctict.izanagi.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMTS = 1;
  public int JJTBLOCK = 2;
  public int JJTWHILEBLOCK = 3;
  public int JJTFUNCBLOCK = 4;
  public int JJTARGUMENTS = 5;
  public int JJTARGUMENT = 6;
  public int JJTSTMT = 7;
  public int JJTDEFFUNC = 8;
  public int JJTCALLFUNC = 9;
  public int JJTIFSTMT = 10;
  public int JJTWHILESTMT = 11;
  public int JJTSELECTSTMT = 12;
  public int JJTDIMSTMT = 13;
  public int JJTBREAKSTMT = 14;
  public int JJTCONTINUESTMT = 15;
  public int JJTPRINTSTMT = 16;
  public int JJTRETURNSTMT = 17;
  public int JJTVOID = 18;
  public int JJTASSIGN = 19;
  public int JJTADDASSIGN = 20;
  public int JJTSUBASSIGN = 21;
  public int JJTMULASSIGN = 22;
  public int JJTDIVASSIGN = 23;
  public int JJTMODASSIGN = 24;
  public int JJTPOWASSIGN = 25;
  public int JJTBAND = 26;
  public int JJTBOR = 27;
  public int JJTEQ = 28;
  public int JJTNEQ = 29;
  public int JJTGE = 30;
  public int JJTGT = 31;
  public int JJTLE = 32;
  public int JJTLT = 33;
  public int JJTADD = 34;
  public int JJTSUB = 35;
  public int JJTMUL = 36;
  public int JJTDIV = 37;
  public int JJTMOD = 38;
  public int JJTPOWER = 39;
  public int JJTAND = 40;
  public int JJTOR = 41;
  public int JJTNOT = 42;
  public int JJTUNIEXPR = 43;
  public int JJTINTEGER = 44;
  public int JJTFLOAT = 45;
  public int JJTSTRING = 46;
  public int JJTVAR = 47;
  public int JJTREFVAR = 48;
  public int JJTSUBSCRIPT = 49;
  public int JJTFUNCNAME = 50;
  public int JJTIDENTIFIER = 51;


  public String[] jjtNodeName = {
    "Start",
    "Stmts",
    "Block",
    "WhileBlock",
    "FuncBlock",
    "Arguments",
    "Argument",
    "Stmt",
    "DefFunc",
    "CallFunc",
    "IfStmt",
    "WhileStmt",
    "SelectStmt",
    "DimStmt",
    "BreakStmt",
    "ContinueStmt",
    "PrintStmt",
    "ReturnStmt",
    "void",
    "Assign",
    "AddAssign",
    "SubAssign",
    "MulAssign",
    "DivAssign",
    "ModAssign",
    "PowAssign",
    "BAnd",
    "BOr",
    "Eq",
    "NEq",
    "Ge",
    "Gt",
    "Le",
    "Lt",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Mod",
    "Power",
    "And",
    "Or",
    "Not",
    "UniExpr",
    "Integer",
    "Float",
    "String",
    "Var",
    "RefVar",
    "Subscript",
    "FuncName",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=8198e66ff79bf58b6a9cfa0d76bcdfc6 (do not edit this line) */
