/* Generated By:JJTree&JavaCC: Do not edit this line. ExprParserConstants.java */
package tk.oknctict.izanagi.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUNC = 5;
  /** RegularExpression Id. */
  int ENDFUNC = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int THEN = 8;
  /** RegularExpression Id. */
  int ELSEIF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int ENDIF = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int ENDWHILE = 13;
  /** RegularExpression Id. */
  int SELECT = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int CASE = 16;
  /** RegularExpression Id. */
  int CASEELSE = 17;
  /** RegularExpression Id. */
  int ENDSELECT = 18;
  /** RegularExpression Id. */
  int DIM = 19;
  /** RegularExpression Id. */
  int AS = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int BREAK = 22;
  /** RegularExpression Id. */
  int CONTINUE = 23;
  /** RegularExpression Id. */
  int PRINT = 24;
  /** RegularExpression Id. */
  int TYPE = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int MINUS = 27;
  /** RegularExpression Id. */
  int MUL = 28;
  /** RegularExpression Id. */
  int DIV = 29;
  /** RegularExpression Id. */
  int MOD = 30;
  /** RegularExpression Id. */
  int POWER = 31;
  /** RegularExpression Id. */
  int AND = 32;
  /** RegularExpression Id. */
  int OR = 33;
  /** RegularExpression Id. */
  int NOT = 34;
  /** RegularExpression Id. */
  int GE = 35;
  /** RegularExpression Id. */
  int LE = 36;
  /** RegularExpression Id. */
  int GT = 37;
  /** RegularExpression Id. */
  int LT = 38;
  /** RegularExpression Id. */
  int EQ = 39;
  /** RegularExpression Id. */
  int NEQ = 40;
  /** RegularExpression Id. */
  int BOOLAND = 41;
  /** RegularExpression Id. */
  int BOOLOR = 42;
  /** RegularExpression Id. */
  int ASSIGN = 43;
  /** RegularExpression Id. */
  int ADDASSIGN = 44;
  /** RegularExpression Id. */
  int SUBASSIGN = 45;
  /** RegularExpression Id. */
  int MULASSIGN = 46;
  /** RegularExpression Id. */
  int DIVASSIGN = 47;
  /** RegularExpression Id. */
  int MODASSIGN = 48;
  /** RegularExpression Id. */
  int POWASSIGN = 49;
  /** RegularExpression Id. */
  int LPAREN = 50;
  /** RegularExpression Id. */
  int RPAREN = 51;
  /** RegularExpression Id. */
  int LBRACKET = 52;
  /** RegularExpression Id. */
  int RBRACKET = 53;
  /** RegularExpression Id. */
  int COMMA = 54;
  /** RegularExpression Id. */
  int STR_START = 55;
  /** RegularExpression Id. */
  int INTEGER = 56;
  /** RegularExpression Id. */
  int FLOAT = 57;
  /** RegularExpression Id. */
  int IDENTIFIER = 58;
  /** RegularExpression Id. */
  int STR = 63;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STR = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Function\"",
    "\"End Function\"",
    "\"If\"",
    "\"Then\"",
    "\"ElseIf\"",
    "\"Else\"",
    "\"End If\"",
    "\"While\"",
    "\"End While\"",
    "\"Select\"",
    "\":\"",
    "\"Case\"",
    "\"Case Else\"",
    "\"End Select\"",
    "\"Dim\"",
    "\"as\"",
    "\"Return\"",
    "\"Break\"",
    "\"Continue\"",
    "\"Print\"",
    "<TYPE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"And\"",
    "\"Or\"",
    "\"Not\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"^=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"\\\"\"",
    "<INTEGER>",
    "<FLOAT>",
    "<IDENTIFIER>",
    "<token of kind 59>",
    "\"\\\\\\\"\"",
    "<token of kind 61>",
    "\"\\\\t\"",
    "\"\\\"\"",
  };

}
